### ISSUE TITLE
username vs mail-adress

### ISSUE THREAD

**Issue by zanglerecke** [texxasrulez/caldav_calendar_te#50]
i use a user-database which is shared between dovecot/roundcube/nextcloud and postfix.
the username is always the full mail adress. 

calcav is using just the username in its query string. As a substitution string. %u gets expanded to the full user@domain adress.

so my configuration at 'caldav_url'   => 'https://nextcloud.mydomain.com/remote.php/dav/calendars/%u/', will not work

i try to implement %user for a replacement... added:
 some line arround 190 in calendar.php:
             $preinstalled_calendars[$index]['caldav_url'] = str_replace('%user', substr($this->rc->get_user_name() , 0, strrpos($this->rc->get_user_name(), '@')) , $cal['caldav_url$

but my conf is still not working  
i will continue posting some results

**Comment by texxasrulez** [comment]
I use full email addresses and have no issues what so ever. Can you provide detailed info? Log files, OS info, etc. The more detailed info you can provide sure will help me out.

**Comment by zanglerecke** [comment]
sorry, logfile not today... i will check
as i read my own text... yes its not very clear:

what i want do do:
i use the full JOHN@domain.at as the username. With that, my mail client can login etc. 
also this same username is the login to the nextcloud BUT it is not the name of the account. this is e.g. just  JOHN. 
so the plugin will search in the path
https://nextcloud.mydomain.com/remote.php/dav/calendars/JOHN@domain.at/
which is not valid. 
-> it has to split off the domain part and use just John...

i try to provide a logfile as soon as possible

**Comment by texxasrulez** [comment]
This plugin uses %u for the username from Roundcube for username, so theoretically, if your Nextcloud account is the same as your users email address without @whatever.com after is, it should work. Log files will help.
