### ISSUE TITLE
UI: "saving data" notification remains visible after failure

### ISSUE THREAD

**Issue by trogper** [texxasrulez/caldav_calendar_te#53]
then saving an event and error occurs while saving it, the notification with loading animation "Saving data..." remains visible
edit: I'm using elastic theme

**Comment by texxasrulez** [comment]
I cannot recreate this.

I have some screenshots of me saving an event with the elastic theme enabled 5 mintues before this posting using latest commit on Github.

Saving Data Notification

![savingdata](https://user-images.githubusercontent.com/10519182/73422131-d0b54380-42dc-11ea-9449-97ffb58a1908.png)

Save Success Notification
![successfullysaved](https://user-images.githubusercontent.com/10519182/73422148-dc086f00-42dc-11ea-8d52-be6526db47e0.png)

Notification Gone

![gone](https://user-images.githubusercontent.com/10519182/73422118-c8f59f00-42dc-11ea-8b89-1ef5324bf7a3.png)

 Can you supply logs to help narrow things down?
I will need your Roundcube Logs, your system logs, your Nextcloud logs (just paste the entries around timeframe of error) and any other thing you may think will be helpful to post. 

I do thank you for your interest.

**Comment by trogper** [comment]
There has to be an error while saving it, not success. Will post the logs later this week

**Comment by trogper** [comment]
this happens for example when I add a calendar with invalid URL. The first error happens immediately after clicking on save, loading spinner is shown, then after a short while error notification shows up with the rest of the log. The error notification disappears after a while, but the pinner one remains.
```
Uncaught Error: cannot call methods on dialog prior to initialization; attempted to call method 'close'
    at Function.error (jquery.min.js?s=1577908862:36)
    at HTMLIFrameElement.<anonymous> (jquery-ui.min.js?s=1577908850:6)
    at Function.each (jquery.min.js?s=1577908862:36)
    at k.fn.init.each (jquery.min.js?s=1577908862:36)
    at k.fn.init.t.fn.<computed> [as dialog] (jquery-ui.min.js?s=1577908850:6)
    at save_func (calendar_ui.js?s=1579871599:2935)
    at HTMLDivElement.click (app.min.js?s=1577908851:306)
    at HTMLButtonElement.<anonymous> (jquery-ui.min.js?s=1577908850:11)
    at HTMLButtonElement.dispatch (jquery.min.js?s=1577908862:36)
    at HTMLButtonElement.v.handle (jquery.min.js?s=1577908862:36)
error @ jquery.min.js?s=1577908862:36
(anonymous) @ jquery-ui.min.js?s=1577908850:6
each @ jquery.min.js?s=1577908862:36
each @ jquery.min.js?s=1577908862:36
t.fn.<computed> @ jquery-ui.min.js?s=1577908850:6
save_func @ calendar_ui.js?s=1579871599:2935
click @ app.min.js?s=1577908851:306
(anonymous) @ jquery-ui.min.js?s=1577908850:11
dispatch @ jquery.min.js?s=1577908862:36
v.handle @ jquery.min.js?s=1577908862:36

POST https://mail.webbox.sk/?_task=calendar&_action=calendar 500 (Internal Server Error)
send @ jquery.min.js?s=1577908862:36
ajax @ jquery.min.js?s=1577908862:36
http_get.http_request @ app.min.js?s=1577908851:330
http_post @ app.min.js?s=1577908851:331
save_func @ calendar_ui.js?s=1579871599:2934
click @ app.min.js?s=1577908851:306
(anonymous) @ jquery-ui.min.js?s=1577908850:11
dispatch @ jquery.min.js?s=1577908862:36
v.handle @ jquery.min.js?s=1577908862:36

XHR failed loading: POST "https://mail.webbox.sk/?_task=calendar&_action=calendar".
```
![image](https://user-images.githubusercontent.com/11559351/73608096-b5895300-45be-11ea-8a93-64912936643f.png)
![image](https://user-images.githubusercontent.com/11559351/73608097-bde18e00-45be-11ea-88a6-d44cbce826f9.png)

**Comment by texxasrulez** [comment]
Why are you trying to add invalid URL's? 
Paste your error log entries from Rouncube, Nextcloud and your server please. Supply system information as well please. OS Ver, PHP Ver, SQL Ver .. 
Is your mail and cloud running on same URL? 
Please provide information.

**Comment by texxasrulez** [comment]
With a database schema contribution from @Offerel it should fix this issue.
