### ISSUE TITLE
Composer dependencies in source code

### ISSUE THREAD

**Issue by LukasK32** [texxasrulez/caldav_calendar_te#61]
Composer dependencies are located in source code in `/calendar/lib/vendor`. I think that it should not be the case and composer should be used to create autoloader and download packages. It will make maintenance easier and the packages could be easily upgraded to new versions further down the line.

I tried removing these packages and got to the point, where everything seems to work and `sabre/dav` (and its dependencies) are managed by composer. However, there are modified duplicates of these packages in `/calendar/lib/vendor/sabre_hybrid` that were created in https://github.com/texxasrulez/caldav_calendar_te/commit/1ad9c197c70fa614fd1830c6d2ab68ae47cf17f8. Added files (compared to `sabre/dav` 3.0.9):

```
./lib/vendor/sabre_hybrid/dav/lib/CalDAV/Backend: SimplePDO.php
./lib/vendor/sabre_hybrid/dav/lib/DAV/Auth/Backend: AbstractBearer.php
./lib/vendor/sabre_hybrid/dav/lib/DAV/Auth/Backend: IMAP.php
./lib/vendor/sabre_hybrid/dav/lib/DAV: ICopyTarget.php
./lib/vendor/sabre_hybrid/dav/lib/DAV: Sharing
./lib/vendor/sabre_hybrid/dav/lib/DAV/Xml/Element: Sharee.php
./lib/vendor/sabre_hybrid/dav/lib/DAV/Xml/Property: Invite.php
./lib/vendor/sabre_hybrid/dav/lib/DAV/Xml/Property: LocalHref.php
./lib/vendor/sabre_hybrid/dav/lib/DAV/Xml/Property: ShareAccess.php
./lib/vendor/sabre_hybrid/dav/lib/DAV/Xml/Request: ShareResource.php
./lib/vendor/sabre_hybrid/dav/lib/DAVACL: ACLTrait.php
./lib/vendor/sabre_hybrid/dav/lib/DAVACL/Xml/Request: AclPrincipalPropSetReport.php
./lib/vendor/sabre_hybrid/dav/lib/DAVACL/Xml/Request: PrincipalMatchReport.php
```
The namespace it these files was not modified and I did not find any requires to them directly. Are these files transplanted from newer release of `sabre/dav`? If the are, maybe it would be better to just upgrade whole project to it?

You can check the progress [here](https://github.com/INDEVOPS/caldav_calendar_te/commits/remove-hardcoded-dependencies).

**Comment by texxasrulez** [comment]
yeah, all that is a WIP... It shouldn't have been uploaded. Too many late nights doing this
