### ISSUE TITLE
local username and domain

### ISSUE THREAD

**Issue by drlight17** [texxasrulez/caldav_calendar_te#63]
Hi!
Did this commit for the issue #29 merged with master branch (https://github.com/texxasrulez/caldav_calendar_te/commit/143d0692d4ca90118c6ddc113dd527c889b12039)? I just don't see the changes in master branch code, but this feature is very important.

**Comment by texxasrulez** [comment]
Thanks for pointing that out. I made some major changes and some older fixes got missed. This was one. This should be fixed in commit 18dc951 and I do thank you for your contribution.
