### ISSUE TITLE
wrong location of composer file

### ISSUE THREAD

**Issue by Miyamoto72** [texxasrulez/caldav_calendar_te#67]
When following install instructions `composer install` will complain about a missing composer.json file since the only file by that name is in the root of the tarball, but not in calendar/ dir:

> host calendar # composer install
> No composer.json in current directory, do you want to use the one at /var/www/rc? [Y,n]? n
> Do not run Composer as root/super user! See https://getcomposer.org/root for details
> Composer could not find a composer.json file in /var/www/rc/plugins/calendar
> To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section

Apparently composer doesn't do anything then in the directory

Steps to reproduce:
download tarball, unpack, copy calendar/, libcalendaring/ and libkolab/ to </path/to/roundcube/>plugins/, cd into plugins/calendar, issue `composer install` command

Debian 10 "Buster", all current updates installed
Composer version 1.9.3

**Comment by texxasrulez** [comment]
I have stated in the README.md to NOT USE COMPOSER TO INSTALL THIS PLUGIN. I know it does not work and it is low on my priority list. I am more concerened with functionality right now and then I will wrap it in a pretty little composer package when that is done ...

**Comment by Miyamoto72** [comment]
I didn't install the plugin using Composer, I merely followed the install instructions. Both README.md as well as detailed_install_instructions.md both have the instruction to invoke `composer install` in the calendar directory.
