### ISSUE TITLE
saving CalDAV cal fails

### ISSUE THREAD

**Issue by Miyamoto72** [texxasrulez/caldav_calendar_te#69]
Just updated to latest version, deleted old plugin folders in <roundcube_dir>/plugins/, copied the latest versions to their place, copied config.inc.php to <roundcube_dir>/plugins/calendar/ and imported the mysql.initial.sql files into the roundcube DB.
Upon invoking `composer install` I ran into the following:
```
host calendar # composer install
Deprecation warning: Your package name texxasrulez/caldav_calendar_te/calendar is invalid, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. The complete name should match "[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9]([_.-]?[a-z0-9]+)*". Make sure you fix this as Composer 2.0 will error.
Deprecation warning: require.texxasrulez/caldav_calendar_te/libcalendaring is invalid, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. The complete name should match "[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9]([_.-]?[a-z0-9]+)*". Make sure you fix this as Composer 2.0 will error.
Deprecation warning: require.texxasrulez/caldav_calendar_te/libkolab is invalid, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. The complete name should match "[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9]([_.-]?[a-z0-9]+)*". Make sure you fix this as Composer 2.0 will error.
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package texxasrulez/caldav_calendar_te/libcalendaring could not be found in any version, there may be a typo in the package name.
  Problem 2
    - The requested package texxasrulez/caldav_calendar_te/libkolab could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

```
I inspected the composer.json in all three dirs. If I'm not mistaken the versions required in calendar/composer.json are higher than the version numbers given in the libkolab and libcalendaring files - just as a side note.

Since the calendar tab appeared in roundcube I tried to add a calendar. NB: It's not a nextcloud CalDAV calendar, it's from SOGo. But it should be standard compliant.

But after filling out the mask and hitting SAVE, I get a save error - and the cal isn't added to the list of calendars. 

Debian Buster, MariaDB 10.3 in a docker container, roundcube 1.4.3, composer 1.9.3

I'm a bit lost what more info you might need, so please tell me, I'll be happy to provide more.

**Comment by texxasrulez** [comment]
You would think it is a standard compliance but that is not the case. That is the reason I started this because I had to fiddle with every other caldav calendar out there to work with nextcloud and thus I only support nextcloud at this time and no dockers. I am open to anyone helping out on this, but I am just one old man doing this
