### ISSUE TITLE
ToDo/Tasks

### ISSUE THREAD

**Issue by ichilver** [texxasrulez/caldav_calendar_te#70]
Does this plugin support ToDo's / Tasks that are stored in a CalDav service?

If so, how do you configure it as I'm clearly missing something?

**#EDIT#**

Think I've answered my question by looking at the Wishlist "Integrate a Caldav Enabled Tasklist plugin."

So the next question is....  What CalDav enabled tasklist plugin were you thinking of integrating?

**Comment by texxasrulez** [comment]
I was thinking about the tasklist plugin that kolab uses. This is WAYYYYYY down the road as I am working on so many repos at the moment. You have any suggestions?
